use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'JWBasicUIKit_Example' do
  pod 'JWBasicUIKit', :path => '../'

  target 'JWBasicUIKit_Tests' do
    inherit! :search_paths

    
  end
end
